<a href="https://colab.research.google.com/github/k4404c/tensorflow_workbook/blob/main/tensorflow0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow 0.0


In [ ]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
# creating tensors
scalar = tf.constant(7)
print(scalar)

tf.Tensor(7, shape=(), dtype=int32)


In [ ]:
#dims of tensor (ndim)
print(scalar.ndim)

0


In [ ]:
#create vector
vector = tf.constant([10,10])
print(vector)
print(vector.ndim)

tf.Tensor([10 10], shape=(2,), dtype=int32)
1


In [ ]:
#create a matrix
matrix = tf.constant([[10,7],
                      [4,4]])
print(matrix)
print(matrix.ndim)

tf.Tensor(
[[10  7]
 [ 4  4]], shape=(2, 2), dtype=int32)
2


In [ ]:
m2 = tf.constant([[4.,4.],
                  [2.,2.],
                  [2.0,-1.3]
                ], dtype= tf.float16)
print(m2)
print(m2.ndim)

tf.Tensor(
[[ 4.   4. ]
 [ 2.   2. ]
 [ 2.  -1.3]], shape=(3, 2), dtype=float16)
2


In [ ]:
#creating a tensor
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9,],[10,11,12]],[[13,14,15],[16,17,18]]])
print(tensor)
print(tensor.ndim)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)
3


* Scalar: single num
* vector: number with direction
* matrix: 2d array
* tensor: n-dim array

### creating tensors with `tf.Variable`

In [ ]:
#create the same tensor as tf.Varaible
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
print(changeable_tensor, '\n', unchangeable_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)> 
 tf.Tensor([10  7], shape=(2,), dtype=int32)


In [ ]:
#change elements of changable
changeable_tensor[0] = 4
print(changeable_tensor)

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
#correct syntax:
changeable_tensor[0].assign(4)
print(changeable_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 7], dtype=int32)>


In [ ]:
#in unchangeable:
unchangeable_tensor[0].assign(4)
print(unchangeable_tensor)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

### Creating random tensors

In [ ]:
#create two random (equal) tensors
rand1 = tf.random.Generator.from_seed(42)
rand1 = rand1.normal(shape=(3,2)) #uses normal distribution for random numbers
print(rand1)
rand2 =  tf.random.Generator.from_seed(42)
rand2 = rand2.normal(shape=(3,2))
print(rand2)

print(rand1==rand2)

#create two random (equal) tensors
rand1 = tf.random.Generator.from_seed(1)
rand1 = rand1.normal(shape=(3,2)) #uses normal distribution for random numbers
#print(rand1)
rand2 =  tf.random.Generator.from_seed(2)
rand2 = rand2.normal(shape=(3,2))
#print(rand2)

print(rand1==rand2)

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[ True  True]
 [ True  True]
 [ True  True]], shape=(3, 2), dtype=bool)
tf.Tensor(
[[False False]
 [False False]
 [False False]], shape=(3, 2), dtype=bool)


### Shuffle order of elements in a tensor

In [ ]:
# shuffle a tensor
not_shuffled = tf.constant([[4,4],
                            [2,3],
                            [0,7]]
                           )
print(not_shuffled)
shuffled = tf.random.shuffle(not_shuffled, seed = 42) #randomly shuffles along first dimension
#notice how even after setting seed values change evertime its run.
#seeds are ran on global and operational level, to change global seed: tf.random.set_seed(42)
print(shuffled)

tf.Tensor(
[[4 4]
 [2 3]
 [0 7]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[2 3]
 [0 7]
 [4 4]], shape=(3, 2), dtype=int32)


In [ ]:
tf.random.set_seed(4)
tf.random.shuffle(not_shuffled, seed = 4)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 4],
       [2, 3],
       [0, 7]], dtype=int32)>

### Creating tensors from numpy arrays

In [ ]:
ones = tf.ones([2,4]) #create tensor of all 1s
print(ones)
zeros = tf.zeros([2,4]) #create tensor of all 1s
print(zeros)

#turn numpy arrays to tensors
#tensors can be run on GPUs much faster!
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
print(numpy_A)
A = tf.constant(numpy_A, shape = (2,3,4)) #we can modify shape, SHAPE MUST LINE UP WITH NUM ELEMENTS
print(A)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(2, 4), dtype=float32)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)


### Getting info from tensors
* shape `tensor.shape`
* rank `tensor.ndim`
* axis / dim `tensor[0]`
* size `tensor.size`

In [ ]:
#create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros([2,3,4,5])
print(rank_4_tensor)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(2, 3, 4, 5), dtype=float32)


In [ ]:
print(rank_4_tensor[0])

tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 4, 5), dtype=float32)


In [ ]:
print(f"shape: {rank_4_tensor.shape}\nndim: {rank_4_tensor.ndim}\nsize:{ tf.size(rank_4_tensor)}")

shape: (2, 3, 4, 5)
ndim: 4
size:120


In [ ]:
#get attributes of tensor:
print("datatype: ", rank_4_tensor.dtype)
print(f"shape: {rank_4_tensor.shape}\nndim: {rank_4_tensor.ndim}\nsize:{ tf.size(rank_4_tensor)}")
print("elements along 0 axis: ", rank_4_tensor.shape[0])
print("elenets along last axis: ", rank_4_tensor.shape[-1])

datatype:  <dtype: 'float32'>
shape: (2, 3, 4, 5)
ndim: 4
size:120
elements along 0 axis:  2
elenets along last axis:  5


### Indexing on tensors
done just like python lists

In [ ]:
#get first 2 elems of each dimension
print(rank_4_tensor[ :2, :2, :2, :2])

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# get first element from each dimension except the final one
print(rank_4_tensor[:1, :1, :1, :])

tf.Tensor([[[[0. 0. 0. 0. 0.]]]], shape=(1, 1, 1, 5), dtype=float32)


In [ ]:
# get first element from each dimension except the second last one
print(rank_4_tensor[:1, :1, :, :1])

tf.Tensor(
[[[[0.]
   [0.]
   [0.]
   [0.]]]], shape=(1, 1, 4, 1), dtype=float32)


In [ ]:
# create a rank 2 tensor
rank2 = tf.constant([[1,2],
                    [4,2]])
print(rank2)
#get last item of each row
print(rank2[:,-1])

tf.Tensor(
[[1 2]
 [4 2]], shape=(2, 2), dtype=int32)
tf.Tensor([2 2], shape=(2,), dtype=int32)


In [ ]:
#add extra dimension to rank2 tensor
rank3 = rank2[...,tf.newaxis] #rank2[:,:, tf.newaxis]
print(rank3)

tf.Tensor(
[[[1]
  [2]]

 [[4]
  [2]]], shape=(2, 2, 1), dtype=int32)


In [ ]:
#alternative:
print(tf.expand_dims(rank2, axis=-1)) #-1 means last axis

tf.Tensor(
[[[1]
  [2]]

 [[4]
  [2]]], shape=(2, 2, 1), dtype=int32)


In [ ]:
#alternative:
print(tf.expand_dims(rank2, axis=0))

tf.Tensor(
[[[1 2]
  [4 2]]], shape=(1, 2, 2), dtype=int32)


### Tensor Operations
* basic operations: `+`,`-`,`*`,`/`

In [ ]:
#you can add values to a tensor using addition operator
tensor = tf.constant([[1,2],[3,4]])
print(tensor)
print(tensor + 10)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[11 12]
 [13 14]], shape=(2, 2), dtype=int32)


In [ ]:
print(tensor - 10)

tf.Tensor(
[[-9 -8]
 [-7 -6]], shape=(2, 2), dtype=int32)


In [ ]:
#we can use tf built in functions too
print(tensor*10)
print(tf.multiply(tensor,10)) #USE THIS IT IS FASTER

tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)


In [ ]:
# Matrix Multiplication
# recall: ixj @ jxk (must be valid for matrix multiplications dimensions)
#recall: resulting matrix will be ixk
print(tensor)
print(tensor * tensor)
print(tensor @ tensor) #python syntax
print(tf.matmul(tensor,tensor)) #tf syntax
print(tf.tensordot(tensor,tensor, axes = 1))

#ifn dif dimensions:
# X @ tf.reshape(Y, shape=(2,3))

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 1  4]
 [ 9 16]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)


In [ ]:
tf.transpose(tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]], dtype=int32)>

### changing dtype


In [ ]:
tensor.dtype

tf.int32

In [ ]:
t = tf.cast(tensor, dtype = tf.int16)
t.dtype

tf.int16

### Tensor Aggregation: condensing from multiple values to 1



In [ ]:
#get abs value
D = tf.constant([4,-4])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 4], dtype=int32)>

In [ ]:
A = tf.constant(np.random.randint(-100.0,100.0, size = 24))
print(A.shape)
print(f"min: {tf.reduce_min(A)}\nmax: {tf.math.reduce_max(A)}\nmean: {tf.reduce_mean(A)}\nsum: {tf.reduce_sum(A)}") #MUST CAST TO REAL NUMBERT TO DO : #\nstd dev: {tf.math.reduce_std(A)}")

(24,)
min: -94
max: 99
mean: -5
sum: -137


In [ ]:
#find positional minimal and maximal
F = tf.random.uniform(shape=[50])
print(F)

#find postitional max
print(tf.argmax(F)) #GIVES INDEX
print(tf.reduce_max(F))

F[tf.argmax(F)] == tf.reduce_max(F)

#use argmin for similar thing

tf.Tensor(
[0.321496   0.014884   0.7265439  0.21229255 0.954177   0.42605257
 0.6750959  0.8877846  0.8355502  0.19438398 0.3097496  0.59535074
 0.11542618 0.00473845 0.10168815 0.13327146 0.03558111 0.06747174
 0.11534369 0.41941416 0.961166   0.16431046 0.2860483  0.24005973
 0.04272425 0.83012426 0.573781   0.72642565 0.8339006  0.5530877
 0.35070598 0.44037795 0.43784916 0.87173223 0.6328505  0.3361994
 0.16131079 0.64460206 0.9205128  0.6613462  0.09610784 0.58244777
 0.78276014 0.868889   0.2035104  0.33408773 0.41502953 0.20325792
 0.14838064 0.8390237 ], shape=(50,), dtype=float32)
tf.Tensor(20, shape=(), dtype=int64)
tf.Tensor(0.961166, shape=(), dtype=float32)


<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Squeezing a tensor (removing all single dimensions

In [ ]:
G = tf.constant(tf.random.uniform(shape=[50]), shape = (1,1,1,1,50))
print(G.shape)
G_squeeze = tf.squeeze(G)
print(G_squeeze.shape)

(1, 1, 1, 1, 50)
(50,)


### One hot encoding (like asscii representation of letters)

In [ ]:
#create list of indeces
some_list = [0,1,2,3] #red green blue purple
tf.one_hot(some_list, depth = len(some_list))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

### squaring, log, sqrt

In [ ]:
H = tf.range(1,10)
print(tf.square(H))
print(tf.sqrt(tf.cast(H , tf.float32))) #method requires non int type
print(tf.math.log(tf.cast(H , tf.float32)))

tf.Tensor([ 1  4  9 16 25 36 49 64 81], shape=(9,), dtype=int32)
tf.Tensor(
[1.        1.4142135 1.7320508 2.        2.236068  2.4494898 2.6457512
 2.828427  3.       ], shape=(9,), dtype=float32)
tf.Tensor(
[0.        0.6931472 1.0986123 1.3862944 1.609438  1.7917595 1.9459102
 2.0794415 2.1972246], shape=(9,), dtype=float32)


### Tensors and Numpy

In [ ]:
J = tf.constant(np.array([1.0,2.0,4.0]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 4.])>

In [ ]:
np.array(J)

array([1., 2., 4.])

In [ ]:
J.numpy()

array([1., 2., 4.])

In [ ]:
J.numpy()[0] #KEEP IN MIND NP HAS DTYPE flaot64, TF HAS DTYPE float32

1.0

### Getting access to GPU

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices()
#if u have a CUDA GPU, tensorflow will use it however possible

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]